# Generated by Django 5.0 on 2025-09-26 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_postings', '0001_initial'),
        ('user_profiles', '0005_jobseekerprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='skills_required',
            field=models.ManyToManyField(blank=True, related_name='jobs_requiring_skill', to='user_profiles.skill'),
        ),
        migrations.AddField(
            model_name='job',
            name='visa_sponsorship',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='work_location',
            field=models.CharField(choices=[('remote', 'Remote'), ('on_site', 'On-site'), ('hybrid', 'Hybrid')], default='on_site', max_length=20),
        ),
    ]
