# Generated by Django 5.2.7 on 2025-10-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_postings', '0011_job_latitude_job_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='address',
            field=models.CharField(blank=True, help_text='Full address for map pinning (optional)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude for map pin (auto-generated from address)', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude for map pin (auto-generated from address)', max_digits=9, null=True),
        ),
    ]
