# Generated by Django 5.2.7 on 2025-10-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_postings', '0012_job_address_alter_job_latitude_alter_job_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='address',
        ),
        migrations.AlterField(
            model_name='job',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude for map pin (auto-generated from location)', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(help_text='Job location (will be used for map pinning)', max_length=500),
        ),
        migrations.AlterField(
            model_name='job',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude for map pin (auto-generated from location)', max_digits=9, null=True),
        ),
    ]
