# Generated by Django 5.0 on 2025-11-23 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_postings', '0011_add_moderation_fields'),
        ('job_postings', '0013_remove_job_address_alter_job_latitude_and_more'),
    ]

    operations = [
    ]
