# Generated by Django 5.0 on 2025-09-25 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0002_skill_jobseekerprofile_education_link_workexperience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='headline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
