# Generated by Django 5.0 on 2025-09-25 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0003_jobseekerprofile_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='updated_at',
        ),
    ]
