# Generated by Django 5.0 on 2025-10-23 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0005_jobseekerprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='is_education_public',
            field=models.BooleanField(default=True, verbose_name='Make Education Public'),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='is_experience_public',
            field=models.BooleanField(default=True, verbose_name='Make Work Experience Public'),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='is_headline_public',
            field=models.BooleanField(default=True, verbose_name="Make 'About Me' Public"),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='is_links_public',
            field=models.BooleanField(default=True, verbose_name='Make Links Public'),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='is_skills_public',
            field=models.BooleanField(default=True, verbose_name='Make Skills Public'),
        ),
    ]
