# Generated by Django 5.0 on 2025-11-16 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0006_jobseekerprofile_is_education_public_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude for your location', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude for your location', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='preferred_location',
            field=models.CharField(blank=True, help_text='Your preferred job search location', max_length=500, null=True),
        ),
    ]
