# Generated by Django 5.2.7 on 2025-11-22 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0007_jobseekerprofile_latitude_jobseekerprofile_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='commute_radius',
            field=models.DecimalField(decimal_places=1, default=25.0, help_text='Preferred commute radius in miles', max_digits=5),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='preferred_location',
            field=models.CharField(blank=True, help_text="Your preferred job search location (e.g., 'Atlanta, GA')", max_length=500, null=True),
        ),
    ]
