# Generated by Django 5.2.7

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profiles', '0008_jobseekerprofile_commute_radius_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedCandidateSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name for this saved search', max_length=200)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('project_keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_checked_at', models.DateTimeField(blank=True, help_text='Last time this search was checked for new matches', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether to check for new matches')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_candidate_searches', to=settings.AUTH_USER_MODEL)),
                ('skills', models.ManyToManyField(blank=True, related_name='saved_searches', to='user_profiles.skill')),
            ],
            options={
                'verbose_name_plural': 'Saved Candidate Searches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_notifications', to='user_profiles.jobseekerprofile')),
                ('saved_search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='user_profiles.savedcandidatesearch')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('saved_search', 'candidate')},
            },
        ),
    ]

